module.exports = {
  SET_USER: "SET_USER",
  SIGN_OUT: "SIGN OUT",
  SHOW_MESSAGE: "[MESSAGE] SHOW MESSAGE",
  HIDE_MESSAGE: "[MESSAGE] HIDE MESSAGE",
  SHOW_AUTH: "[AUTH] SHOW AUTH",
  HIDE_AUTH: "[AUTH] HIDE AUTH",
};
